GAME_CHANNEL = '#triviachannel'
ADMINS = ['admin']
Q_DIR = './questions/'
SAVE_DIR = './savedata/'
IDENT_STRING = 'password'
WAIT_INTERVAL = 30
COLOR_CODE = '\00308,01 '
LINE_RATE = 0.4
DEFAULT_NICK = 'triviabot'
SERVER = 'irc.freenode.net'
SERVER_PORT = 6667
